Add checks for the rnnoise ladspa lib

diff --git a/rnnoise_loader b/rnnoise_loader
--- a/rnnoise_loader
+++ b/rnnoise_loader
@@ -9,7 +9,7 @@ DEST="pacmd"
 LADSPA_LIB=librnnoise_ladspa.so
 SOURCE="$(pactl info | grep 'Default Source' | tr -d ' ' | cut -d ':' -f2)"
 
-while getopts ':humspl:c:' opt; do
+while getopts ':humspfl:c:' opt; do
   case ${opt} in
     h )
       echo "Usage: $(basename "$0") [-u] [-m] [-s] [-p] [-c value]"
@@ -22,6 +22,7 @@ while getopts ':humspl:c:' opt; do
       echo -e "  -c \tSet RNNoise control, in percent (default: 95)"
       echo -e "  -p \tOnly print PulseAudio commands, do not execute them (pipe mode)"
       echo -e "  -l \tProvide path to librnnoise_ladspa.so (by default the standard ladspa lib path will be used)"
+      echo -e "  -f \tForce loading, disable checks if ladspa library is valid"
       echo -e "  -h \tShow this help and exit"
       echo ""
       echo "Notes:"
@@ -51,6 +52,9 @@ while getopts ':humspl:c:' opt; do
       ;;
     l )
       LADSPA_LIB="$OPTARG"
+      ;;
+    f )
+      FORCE_LADSPA=1
       ;;
     \? )
       echo "Invalid option: $OPTARG" >&2
@@ -91,6 +95,20 @@ unload_speaker (){
 if [ $UNLOAD -eq 0 ]
 then
   # Loading modules
+  if [ -z $FORCE_LADSPA ]
+  then
+    if ! { { listplugins 2>> /dev/null | grep -q "$LADSPA_LIB" ;} || [ -f "$LADSPA_LIB" ]; }
+    then
+      echo "Ladspa: library '${LADSPA_LIB}' not found" >&2
+      exit 2
+    fi
+    if ! { analyseplugin "$LADSPA_LIB" | grep -q "noise_suppressor_mono"; }
+    then
+      echo "Ladspa: Label 'noise_suppressor_mono' not found in plugin '${LADSPA_LIB}'" >&2
+      exit 3
+    fi
+  fi
+
   if [ $MIC -eq 1 ]
   then
     unload_mic
